### PR TITLE
Add ember-octane scenario

### PR DESCRIPTION
**Pull request by mwpastore**

### CODE REVIEW

**Comment by ryanto** [comment]
Hi Mike! Thanks for adding this! 👍👍👍 

I'd like to get the octane scenario passing before merging this, does that sound ok? My guess is that we're relying on some jquery/ajax for our FastBoot ED adapter, but I'm traveling this week and am offline until 4/1.

**Comment by ryanto** [comment]
Hey @mwpastore 

I pulled this down and gave it a look, thanks again for adding it!

Our docs use liquid-fire to do some animation and that library depends on jQuery, so we'll have to add `@ember/jquery` and turn on `jquery-integration` in order to get this passing. Hopefully, that's enough to get the tests green. 

If you want to make this change I can merge this once the tests pass.

**Comment by mwpastore** [comment]
If we re-enable jQuery, there's no functional difference between this scenario and the ember-canary one (that I'm aware of), so let's just skip it. Thanks Ryan!

**Comment by ryanto** [comment]
Yup, I see that because our docs depend on lf/jQuery it puts us in a strange place... we can't actually test against a vanilla octane app.

**Pull request closed without merging**
