### PR TITLE
Give #load control of background reloading

### PR DESCRIPTION
**Pull request by ryanto**

### CODE REVIEW

**Comment by Gaurav0** [comment]
Using this. Can you merge it?

**Comment by ryanto** [comment]
Thanks for the reminder Gaurav! I'll get this merged soon, but first I want to make sure we can have a consistent API across `load`, `loadRecord`, etc. Also, I need to add docs for this. 

Once those are done I'll get this merged.

I'll leave this branch live on Github, so feel free to depend on it.

**Comment by Gaurav0** [comment]
Thanks @ryanto. I set up my fork here but needs more tests (and of course docs):

**Comment by ryanto** [comment]
Closing in favor of https://github.com/embermap/ember-data-storefront/pull/74 which covers this use case

**Pull request closed without merging**
